name: Tomas Enhager
favicon: null
layout_spectrum: 0
typography_spectrum: 0.56761
title: "Utbildare |\_Föreläsare |\_Livscoach"
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#b4c5d5'
    - '#251c13'
    - '#324357'
    - '#7c5d00'
    - '#efe6d3'
  brandStrength: 0.5
  lightness: 0.625
  saturation: 0.375
  rhythmicContrast: 0.5
purpose: []
