name: Tomas Enhager
favicon: null
layout_spectrum: 0.34109
typography_spectrum: 1
title: "Tomas Enhager - Utbildare |\_Föreläsare |\_Livscoach"
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#dfdfdf'
    - '#2d2c34'
    - '#bfbcb7'
    - '#bd9264'
    - '#76432f'
  brandStrength: 0.6875
  lightness: 0.16200023074634373
  saturation: 0.875
  rhythmicContrast: 0.2092496594414115
purpose: []
