name: Tomas Enhager
favicon: null
layout_spectrum: 1
typography_spectrum: 0.56761
title: "Tomas Enhager - Utbildare |\_Föreläsare |\_Livscoach"
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#d0d0d0'
    - '#959595'
    - '#fdfdfd'
    - '#382b22'
    - '#5e554e'
  brandStrength: 0.5
  lightness: 0.625
  saturation: 0.3125
  rhythmicContrast: 0.5
purpose: []
