name: Tomas Enhager
favicon: null
layout_spectrum: 1
typography_spectrum: 0.75292
title: "Tomas Enhager - Utbildare |\_Föreläsare |\_Livscoach"
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#dfdfdf'
    - '#2d2c34'
    - '#bfbcb7'
    - '#bd9264'
    - '#76432f'
  brandStrength: 0.8125
  lightness: 0.6875
  saturation: 0.5
  rhythmicContrast: 0.25
purpose: []
